# Generated by Django 5.2.6 on 2025-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The brand or generic name of the medicine.', max_length=200)),
                ('composition', models.CharField(help_text="The active ingredients and their strength (e.g., 'Paracetamol 500mg').", max_length=255)),
                ('administration_type', models.CharField(choices=[('oral', 'Oral'), ('inj', 'Injection'), ('topical', 'Topical'), ('inhal', 'Inhalation')], default='oral', help_text='How the medicine is administered.', max_length=10)),
                ('category', models.CharField(help_text="The therapeutic category (e.g., 'Analgesic', 'Antibiotic').", max_length=100)),
                ('count_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('ampoule', 'Ampoule'), ('vial', 'Vial'), ('bottle', 'Bottle'), ('tube', 'Tube')], default='tablet', help_text='The unit of the medicine (e.g., tablet, bottle).', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The total quantity currently in stock.')),
                ('expiration_date', models.DateField(help_text='The expiration date of the medicine batch.')),
                ('remarks', models.TextField(blank=True, help_text='Any additional notes or remarks.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name', 'composition'],
            },
        ),
    ]
