# Generated by Django 5.2.6 on 2025-09-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Set a number to get a low stock warning when quantity falls to or below this.'),
        ),
    ]
